FROM node:18-alpine AS build

ARG REDIS_URL
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_DSN
ARG SENTRY_LOG_LEVEL=warn
ARG NODE_ENV=production
ARG X_API_KEY
ARG CMS_URL
ARG RELEASE_TAG_NAME

# Build args for browser variables
ARG NEXT_PUBLIC_MAINNET_API_SERVER
ARG NEXT_PUBLIC_TESTNET_API_SERVER
ARG NEXT_PUBLIC_LEGACY_EXPLORER_API_SERVER
ARG NEXT_PUBLIC_DEPLOYMENT_URL
ARG NEXT_PUBLIC_MAINNET_ENABLED
ARG NEXT_PUBLIC_DEFAULT_POLLING_INTERVAL

WORKDIR /app

COPY . .

RUN npm install -g pnpm@8.9.1
RUN pnpm i
RUN pnpm build

FROM node:18-alpine

ARG REDIS_URL
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_DSN
ARG SENTRY_LOG_LEVEL=warn
ARG NODE_ENV=production

# Set ENVs so they persist after image is built
ENV NEXT_SHARP_PATH=/tmp/node_modules/sharp
ENV REDIS_URL=${REDIS_URL}
ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
ENV SENTRY_DSN=${SENTRY_DSN}
ENV SENTRY_LOG_LEVEL=${SENTRY_LOG_LEVEL}
ENV NODE_ENV=${NODE_ENV}
ENV X_API_KEY=${X_API_KEY}
ENV CMS_URL=${CMS_URL}
ENV RELEASE_TAG_NAME=${RELEASE_TAG_NAME}

WORKDIR /app

COPY --from=build /app/next.config.js /app/next.config.js
COPY --from=build /app/public /app/public
COPY --from=build /app/.next/static /app/.next/static
COPY --from=build /app/.next/standalone /app


EXPOSE 3000
CMD [ "node", "server.js" ]
