export const TX_TABLE_PAGE_SIZE = 25;
export const ADDRESS_ID_PAGE_ADDRESS_TXS_LIMIT = 10;
export const ADDRESS_ID_PAGE_RECENT_ADDRESS_TXS_LIMIT = 3;
export const ADDRESS_ID_PAGE_FUNGIBLE_TOKENS_LIMIT = 10;
