name: Code checks

on: [pull_request]

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare testing env
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.9.0'
      - run: pnpm i
      - name: Run unit tests
        run: pnpm run test:unit
