name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre_run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@ad6cb1b847ffb509a69b745b6ee2f1d14dfe14b8
        with:
          access_token: ${{ github.token }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.9.0'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Prettier
        run: pnpm add prettier@2.8.1
      - name: Lint Prettier
        run: pnpm run lint:prettier
        env:
          CI: true
